### ISSUE TITLE
Display improvement

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#157]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
- In Firefox browser, application icons are too small.
- In published parameters graphs, reverse data order : put publishable on the top of diagram
- In unused elements information icon, replace "an option" with "any option"
- in Model Dashboard, change colours used to adapt for colour-blind people
- reverse colors for Switch Mode Tooltip component : grey for server switch mode value, green for others
- in Parameter Editor and Subscription Dashboard, put switch mode icon in same color than in switch mode tooltip

### Steps to Reproduce
NA

### Logs
NA 
  
### System Configuration
NA

**Comment by samatrhea** [comment]
after the refactoring this issue is no longer valid
