### ISSUE TITLE
Manual fetch data from data source

### ISSUE THREAD

**Issue by jaimeatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#167]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The user shall have a button to manually fetch data from source so the Viewer can be updated.

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration
NA

**Comment by samatrhea** [comment]
The application already has a function that allows a user to update manualy data from a COMET server:

![image](https://user-images.githubusercontent.com/22165725/196008335-ecc0911d-0823-4eb7-9910-2ada8fd5a69f.png)

Is this what you require here? or something else?
