### ISSUE TITLE
WebPermissionIssues

### ISSUE THREAD

**Issue by abwise** [RHEAGROUP/COMET-WEB-Community-Edition#222]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When on the comet web app the permissions do not seem to be working properly. When trying to change permissions the only one able to see anything in the web app is the model administrators. In the desktop comet app an observer can view but not edit elements. I would like for this to be possible in the web app as well. 

### Logs

  - [x] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
  <img width="960" alt="ObserverWebPermissions" src="https://user-images.githubusercontent.com/46786468/210828101-1f501a1d-1b83-4b99-9e7b-0f337a6f320c.PNG">
<img width="568" alt="ObserverModel" src="https://user-images.githubusercontent.com/46786468/210829229-37372489-ddba-4865-be3b-91b37ce36746.PNG">

### System Configuration

- COMET version:
  - [x] COMET-WEB: 0.22.0.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

**Comment by samatrhea** [comment]
This will be 100% fixed in the next major release and is being fixed in the refactoring that is ongoing in #239
