### ISSUE TITLE
Add ViewModels Support

### ISSUE THREAD

**Issue by jaimeatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#228]
### Prerequisites

- [x] I have written a descriptive issue title
- [x} I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
For the moment COMET-WEB is not using ViewModels. Refactor to be able to use ViewModels with ReactiveUI

**Comment by samatrhea** [comment]
this is a duplicate of #231
