### ISSUE TITLE
Compare primitives instead of comparing ParametersValues

### ISSUE THREAD

**Issue by jaimeatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#240]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently to see if a Primitive has suffered changes and that those changes haven't been summited, a comparison of the IValueSet related to a specific ParameterBase it's done. However the comparison should be at entity level. This should decouple the components event more.

**Comment by samatrhea** [comment]
no longer relevant
