### ISSUE TITLE
[System Representation] improvements - spacing, editor, treeview choice

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#348]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The System Representation page can use some use some visual improvements:

1. The treeview is different than the one in the 3D viewer. We should use the same one i think, or they should at least look the same. I have no strong preference which one should stay
2. the spacing between the tree and the details panel is far too large. This needs to be organized in a different fashion. 
3. The title of the details panels states "Element Definition", the Type states "ElementUSag". I propose that the title is renamed to "Building Block"

![image](https://user-images.githubusercontent.com/22165725/233409359-f5f241f2-1cec-45eb-b5c2-05edbf92cb24.png)

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-WEB: 1.0.1

**Comment by lxatrhea** [comment]
@antoineatrhea Please create separate issues when necessary.
