### ISSUE TITLE
[Model Editor] Add details panel editor

### ISSUE THREAD

**Issue by nabilatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#373]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

see issue #372  (which needs to be implemented first) for the page where all the Element definitions are shown

- [x] When a row is selected (could be source, or target) we should be able to see its details on the right
- [x] User should be able to edit  or create element definition
- [x] add unit tests to view-model (nunit) and view (bunit)
### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-WEB: 
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

**Comment by lxatrhea** [comment]
@samatrhea @antoineatrhea @nabilatrhea Please discuss the implementation here. Could be done in a lot of different ways.
