### ISSUE TITLE
[Subscription Dashboard] As a domain expert, I want to visualize my parameter subscription 

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#40]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Create a table with my subcribed values
 
### Steps to Reproduce
NA

### Logs
NA

### System Configuration
NA

**Comment by nlesa** [comment]
## Description
Parameter subscriptions should be clearly visible on the subscription dashboard and update automatically with COMET model publications.

## Steps to reproduce
1. Login as a domain expert
2. Navigate to the subscription dashboard
3. Check that subscriptions are shown
4. Go to COMET and add one new subscription and remove one old subscription.
6. Check that the subscription dashboard on the web app updated accordingly

## Test data / logs
I can see the subscriptions, however the only way I can get them to update is to close and reopen the model. Switching applications does not cause any updates and reloading the page causes me to be logged out entirely.

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.13.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version: http://comet-web.go.esa.int:5000/

**Comment by nlesa** [comment]
Previous comment was resolved by updating the COMET web app version

**Comment by nlesa** [comment]
## Description
Parameter subscriptions should be clearly visible on the subscription dashboard and update automatically with COMET model publications.

## Steps to reproduce
1. Login to COMET as a domain expert
2. Open a model
3. Open the subscription dashboard
4. Check all subscriptions appear in the table

## Test data / logs
Subscription to parameter overrides (found in the Element Usages) do not appear on the subscription dashboard anywhere

## System configuration
- COMET version:
  - [ ] COMET-WEB: 
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

**Comment by samatrhea** [comment]
dear @nlesa when you find issues, feel free to create new tickets. These follows will be very difficult to trace.
