### ISSUE TITLE
[Subscription Dasboard] As a domain expert, I want to know when my parameter subscription changed

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#41]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Highlight when a subcription changed :
- on a defined period (menu with several periods)
- between 2 connection (Save dates of connection + Compare with date from publication)

### Steps to Reproduce
NA

### Logs
NA  
  
### System Configuration
NA

**Comment by nlesa** [comment]
## Description
When a subscribed value changes this should be highlighted in the subscription list on the subscription dashboard.

## Steps to reproduce
1. Login as a domain expert
2. Navigate to the subscription dashboard
3. Check that subscriptions are shown
4. Go to COMET and update at least one value that is subscribed to.
5. Ensure changes in COMET are published
6. Check that the subscription dashboard highlights the updated subscriptions clearly

## Test data / logs
Updated a value and it did update on the web app but there was no notification of the change or highlighting of the change on the subscription dashboard

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.13.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version: http://comet-web.go.esa.int:5000/
