### ISSUE TITLE
[Add] MessagePack deserilizer

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#417]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
upgrade to CDP4ServicesDal-CE version

related to  https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues/266
  
### System Configuration

- COMET version: 1.3.0

**Comment by samatrhea** [comment]
in principle this is automatically taken care of using the SDK that is now being used 26.x.y, so i think we can close it but just make sure this is indeed working as expected.

**Comment by joao4all** [comment]
I can confirm that Comet-Web is using the messagepack deserializer

![image](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/assets/140734849/012118aa-6b60-4512-b06e-f69aea874779)
