### ISSUE TITLE
direct inclusion of external web resources

### ISSUE THREAD

**Issue by nlmave** [RHEAGROUP/COMET-WEB-Community-Edition#420]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The Comet WebApp root web response dynamically includes the following scripts from external domains:

https://preview.babylonjs.com/babylon.js
https://preview.babylonjs.com/loaders/babylonjs.loaders.min.js

This makes the Web app vulnerable to changes in babylon.js, both functional and potentially malicious ones.
Both for stability and security reasons, the babylon.js library should be hosted locally from the COMET WebApp docker container.

### Steps to Reproduce

Check your code for fragments like:
```
</script>
    <script src="https://preview.babylonjs.com/babylon.js"></script>
    <script src="https://preview.babylonjs.com/loaders/babylonjs.loaders.min.js">
</script>
```

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-WEB: 1.3.0
  - [ ] Other: 
- Web Services:
  - [x] COMET Web Services version: 7.1.1

**Comment by nlmave** [comment]
Alternately, add a subresource integrity attribute to the script tag along with a base64 encoded cryptographic hash value, if direct / local hosting of babylon.js is not suitable.

**Comment by samatrhea** [comment]
@jaimeatrhea or @antoineatrhea , please update accordingly so the webapp is no longer dependent on external resources which is indeed better to prevent vulnerabilities and have more control over which version we want to distribute

**Comment by nlmave** [comment]
Also check ./robots.txt seems to have same issue?
