### ISSUE TITLE
[Parameter Editor] Changes are not easy to keep track of

### ISSUE THREAD

**Issue by LorenzoBichisao-ESA** [RHEAGROUP/COMET-WEB-Community-Edition#428]
It would be nice if the user was given some sort of feedback when a value is changed. For example the value could go blue like in the IME.

**Comment by samatrhea** [comment]
Suggested improvements:

- [ ] when a Parameter is publishable, the font shall be set to bold-blue.

NOTE: A parameter is publishable when the **actualValue** is not equal to the **published** value
