### ISSUE TITLE
[Subscription Dashboard] As a domain expert, I want to visualize the evolution of a parameter

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#43]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Graph with evolution of a paramater : get all values for selected parameter and do the graph
Feature for my parameters and my subscription
(add little graph on the table : click on it = zoom)

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration
NA

**Comment by nlesa** [comment]
## Description
It should be possible to view the history of a parameters values to see how it has evolved over time

## Steps to reproduce
1. Login as a domain expert
2. Navigate to the subscription dashboard
3. Check that subscriptions are shown
4. Go to COMET and update at least one value that is subscribed to.
5. Ensure changes in COMET are published
6. Check that on the subscription dashboard the previous value can still be found in the history of that parameter.

## Test data / logs
Cannot see anyway to see the history. Tried clicking on the value and on the value column, only see the table with subscriptions.

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.13.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version: http://comet-web.go.esa.int:5000/

**Comment by nlesa** [comment]
Previous Comment was resolved by updating the COMET Web version

**Comment by nlesa** [comment]
## Description
It should be possible to view the history of a parameters values to see how it has evolved over time. I found that if in the value history the value goes back to the default '-' this causes an error.

## Steps to reproduce
1. Login as a domain expert
2. Navigate to the subscription dashboard
3. Check that subscriptions are shown
4. Go to COMET and update at least one value that is subscribed to a number
5. Ensure COMET web app refreshes to update the change
6. Update the value on COMET to the default '-'
7. Ensure COMET web app refreshes to show the change
8. Click on the value history

## Test data / logs

```
blazor.webassembly.js:1 
crit: 
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Format_InvalidString
System.FormatException: Format_InvalidString
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseDouble(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Double.Parse(String s)
   at COMETwebapp.Pages.SubscriptionDashboard.ParameterEvolution.LoadData()
   at COMETwebapp.Pages.SubscriptionDashboard.ParameterEvolution.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.16.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:
