### ISSUE TITLE
[Book application] Create small application to manage books

### ISSUE THREAD

**Issue by jaimeatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#451]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Create a small application to manage books and the information related to them.

**Comment by samatrhea** [comment]
@jaimeatrhea is this done?

**Comment by jaimeatrhea** [comment]
Yeah, I'm closing it
