### ISSUE TITLE
[Parameter Editor] when the user clicks on the "Add an ElementDefinition" button an unhandled error occurs

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#523]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce
  - login to https://cdp4services-public.cdp4.org using admin/pass
  - open the LOFT model
  - navigate to the Parameter Editor
  - click on the "add an element definition" button

Notice that the application is faced with an unhandled error

### Logs
NA
  
### System Configuration

- COMET version:
  - [x] COMET-WEB: 2.0.1

**Comment by antoineatrhea** [comment]
The "Add an ElementDefinition" functionality has been moved to the ModelEditor application. This button have to be removed from the ParameterEditor

**Comment by samatrhea** [comment]
feel free to remove it
