### ISSUE TITLE
As a user i want to enable/disable auto-refresh and do a manual refresh

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#57]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
  [] add a settings page (triggered from the user profile) to enable or disable autorefresh and to set the refresh time expressed in seconds
  [] on the top menu bar, add a button to manually refresh the data

**Comment by nlesa** [comment]
## Description
It should be possible to choose between a manual refresh and an auto refresh to update the values on the web app to be inline with COMET. Choosing a manual refresh the web app only updates when I refresh it and when I do refresh it the values match those in COMET

## Steps to reproduce
1. Login as any user
2. Make sure auto-refresh is off
3. Make a change in COMET ensuring it is published
4. Manually refresh the web app
5. Verify the web app is updated

## Test data / logs
Blocked. I cannot see a manual refresh option on the page and clicking the browser refresh button causes an error and for me to be logged out. 

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.13.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version: http://comet-web.go.esa.int:5000/

**Comment by samatrhea** [comment]
@nlesa can you confirm that you see the refresh page in the user settings dialog?

![image](https://user-images.githubusercontent.com/22165725/180948164-9089a227-97cd-4d8f-af83-a3555de5392f.png)

**Comment by nlesa** [comment]
I confirm that I can now see the refresh page in the user settings dialog and I can see the manual button. However the auto-refresh is not working for me in 0.16.0, shall I create a new ticket or is this issue already known?

**Comment by nlesa** [comment]
I see the refresh page in the user settings on 0.16.0. 

I do now have some issues with it continuing to refresh sometimes when the box has been unticked but I think you were already aware of this issue? Or should I create a new ticket?
