### ISSUE TITLE
[Model Dashboard] As a user, I want a general dahsboard with all information

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#59]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Create general dashboard

### Steps to Reproduce
NA

### Logs
NA 
  
### System Configuration
NA

**Comment by nlesa** [comment]
## Description
[Model Dashboard] As a user, I want a general dashboard with all information

## Steps to reproduce
Blocked

## Test data / logs
Blocked. Not sure what is covered under "All Information" so cannot test.

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.13.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version: http://comet-web.go.esa.int:5000/
