### ISSUE TITLE
Switch the application from client-side to server-side

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#67]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Switch the application from client-side to server-side

Take into account thread safety when using this.StateHasChanged().
https://blazor-university.com/components/multi-threaded-rendering/invokeasync/

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration
- COMET version:
  - [x] COMET-WEB:  0.2.0

**Comment by antoineatrhea** [comment]
Closed in favor of #494
