### ISSUE TITLE
Auto-refresh in settings page

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#70]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Add a settings page (triggered from the user profile) to enable or disable autorefresh and to set the refresh time expressed in seconds

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration
NA

**Comment by nlesa** [comment]
## Description
Within the user settings there should be an option to auto-refresh the page

## Steps to reproduce
1. Login as any user
2. Click the settings button
3. Select Auto-refresh

## Test data / logs
Blocked. I cannot see a settings page

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.13.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version: http://comet-web.go.esa.int:5000/

**Comment by nlesa** [comment]
## Description
Within the user settings there should be an option to  choose how often to auto-refresh the page

## Steps to reproduce
1. Login as any user
2. Click the settings button
3. Select Auto-refresh time

## Test data / logs
Blocked. I cannot see a settings page

## System configuration
- COMET version:
  - [ ] COMET-WEB: 0.13.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version: http://comet-web.go.esa.int:5000/

**Comment by samatrhea** [comment]
![image](https://user-images.githubusercontent.com/22165725/179243385-15a0d845-d3ca-4d45-8dec-3c2b6359cd47.png)

should be working

**Comment by samatrhea** [comment]
@nlesa can you confirm to see this in version 0.16.0?

**Comment by nlesa** [comment]
Updating the COMET web app version resolved the comments I made above that I could not see the settings page, I now see it
